// <auto-generated />
using System;
using HiHSK.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiHSK.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110000005_SeedWordExamplesHsk1Topic1")]
    partial class SeedWordExamplesHsk1Topic1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Migration này chỉ seed data, không thay đổi model
            // Model đã được định nghĩa trong các migration trước
        }
    }
}

